# Documentar Componente Individual - Workflow Configuration
name: documentar-componente
description: "Documentar un componente de software específico del sistema, creando documentación técnica completa que sirva como guía práctica para desarrolladores y operadores"
author: "Método Ceiba - Arquitecto"

# Critical variables
config_source: "{project-root}/.ceiba-metodo/metodo-ceiba/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
architecture_sharded_location: "{config_source}:architecture_sharded_location"

# Module path and component files
installed_path: "{project-root}/.ceiba-metodo/metodo-ceiba/workflows/arquitectura/documentar-componente"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{architecture_sharded_location}/architecture-{{component_name}}.md"

# Component analysis variables (will be elicited)
component_name: "{{component_name}}"
component_path: "{{component_path}}"
component_type: "{{component_type}}"
technologies: "{{technologies}}"
purpose: "{{purpose}}"
