# <!-- Powered by BMAD™ Core -->
name: ceiba-metodo
version: 4.43.33
short-title: Método Ceiba
description: >-
  Framework de desarrollo ágil especializado basado en metodología Ceiba.
  Proporciona agentes especializados, flujos de trabajo y herramientas 
  para equipos de desarrollo fullstack siguiendo los principios y 
  prácticas del Método Ceiba. Incluye arquitecto, peer reviewer,
  y procesos de refinamiento de historias de usuario estructurados.
author: Ceiba Software
slashPrefix: ceiba

# Configuración base heredada de BMAD Core
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
